name: Build and Test on Windows

on:
  pull_request:
    branches: ['main']

defaults:
  run:
    shell:
     powershell Invoke-Expression -Command "./spack/share/spack/setup-env.ps1"; {0}

jobs:
  build-and-test:
    runs-on: windows-latest
    permissions:
      packages: write

    steps:
    - name: Checkout Quandary
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout Spack
      uses: actions/checkout@v4
      with:
        ref: rsc-2025-03-0
        repository: spack/spack
        path: spack

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: |
        python -m pip install --upgrade pip six pywin32 setuptools coverage
        python -m pip install -e . --prefer-binary

    - name: Install diffutils
      run: choco install diffutils -y

    - name: Install OneApi fortran compiler
      env:
        ONEAPI_FORTRAN_URL:
          https://registrationcenter-download.intel.com/akdlm/IRC_NAS/f6a44238-5cb6-4787-be83-2ef48bc70cba/w_fortran-compiler_p_2024.1.0.466_offline.exe
      run: |
          curl -SL --output oneapi_installer.exe %ONEAPI_FORTRAN_URL%
          start /w oneapi_installer.exe -s --remove-extracted-files yes -a --silent --eula accept
          del oneapi_installer.exe
      shell: cmd

    - name: Spack configuration
      run: |
        echo "SPACK_COLOR=always" >> "$GITHUB_ENV"
        echo "SPACK_DISABLE_LOCAL_CONFIG=1" >> "$GITHUB_ENV"
        spack -e .spack_env mirror set binary_mirror --unsigned
        spack mirror add --type binary --unsigned --oci-username GITHUB_USER --oci-password-variable GITHUB_TOKEN local-buildcache oci://ghcr.io/tdrwenski/spack-buildcache
        spack compiler find
        spack external find cmake ninja win-sdk win-wdk wgl msmpi diffutils python

    - name: Build Quandary
      run: |
        spack -e .spack_env concretize
        spack -e .spack_env -v install --use-buildcache package:never

    - name: Run regression tests
      run: |
        spack env activate .spack_env
        cp $(which quandary) .
        pytest -v -s tests

    - name: Push packages and update index
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: spack -e .spack_env buildcache push --update-index local-buildcache
      if: ${{ !cancelled() }}
